PRINT 'Running 360_MasterList.TopLevelDomain.sql';

SET NOCOUNT ON;

BEGIN TRY

  BEGIN TRANSACTION;

  -- Our script user id = -1
  DECLARE @CreatedByTopLevelDomain INT;
  SET @CreatedByTopLevelDomain = 1;

  -- Active Row Status
  DECLARE @activeTopLevelDomain INT;
  SET @activeTopLevelDomain = 8;

  -- If the record is found, indicate as a status 250 in our output
  DECLARE @RecordExistsTopLevelDomain INT;
  SET @RecordExistsTopLevelDomain = 250;

  -- Create a table to hold the data we are going to load. All columns except the hashbytes column should be included
  DECLARE @DataLoadTopLevelDomain AS TABLE
  (
    [RowCounter]                INT           NOT NULL IDENTITY(1,1),
    [RowStatus]                 tinyint       NOT NULL,
    [TopLevelDomain]            varchar(24)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TopLevelDomainType]        varchar(64)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TopLevelDomainDescription] varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
  );

  -- Create a table to hold out output
  DECLARE @DataLoadTopLevelDomainOutput AS TABLE
  (
    [TopLevelDomain]            [varchar](24) NOT NULL,
    [RowStatus]                 [tinyint] NOT NULL,
    [CreatedBy]                 [uniqueidentifier] NOT NULL,
    [ModifiedBy]                [uniqueidentifier] NOT NULL,
    [CreatedDate]               [DATETIMEOFFSET] NOT NULL,
    [ModifiedDate]              [DATETIMEOFFSET] NOT NULL,
    [RowGuid]                   [uniqueidentifier] ROWGUIDCOL  NOT NULL,
    [TopLevelDomainType]        [varchar](64)  NULL,
    [TopLevelDomainDescription] [varchar](1000) NULL
  );

  -- We need a loop counter var
  DECLARE @CtrTopLevelDomain INT;
  SET @CtrTopLevelDomain = 0;

  -- Bulk load the data we wish to try and insert to our data loader table
  INSERT INTO @DataLoadTopLevelDomain ( RowStatus, TopLevelDomain, TopLevelDomainType, TopLevelDomainDescription )
  VALUES 
( @activeTopLevelDomain, '.', 'Original', 'Default Blank' ),
( @activeTopLevelDomain, 'com', 'Original', 'commercial' ),
( @activeTopLevelDomain, 'org', 'Original', 'organization' ),
( @activeTopLevelDomain, 'net', 'Original', 'network' ),
( @activeTopLevelDomain, 'int', 'Original', 'international organizations' ),
( @activeTopLevelDomain, 'edu', 'Original', 'education' ),
( @activeTopLevelDomain, 'gov', 'Original', 'U.S. national and state government agencies' ),
( @activeTopLevelDomain, 'mil', 'Original', NULL ),
( @activeTopLevelDomain, 'arpa', 'Infrastructure', NULL ),
( @activeTopLevelDomain, 'abc', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'academy', 'ICANN-era Generic - English', 'academic institutes' ),
( @activeTopLevelDomain, 'accountant', 'ICANN-era Generic - English', 'accountants and accounting firms' ),
( @activeTopLevelDomain, 'accountants', 'ICANN-era Generic - English', 'accountants and accounting firms' ),
( @activeTopLevelDomain, 'active', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'actor', 'ICANN-era Generic - English', 'actors' ),
( @activeTopLevelDomain, 'ads', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'adult', 'ICANN-era Generic - English', 'adult entertainment (pornography)' ),
( @activeTopLevelDomain, 'aero', 'ICANN-era Generic - English', 'air-transport industry' ),
( @activeTopLevelDomain, 'agency', 'ICANN-era Generic - English', 'business associations' ),
( @activeTopLevelDomain, 'airforce', 'ICANN-era Generic - English', 'defense contractors' ),
( @activeTopLevelDomain, 'analytics', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'apartments', 'ICANN-era Generic - English', 'apartments' ),
( @activeTopLevelDomain, 'app', 'ICANN-era Generic - English', 'Phone apps' ),
( @activeTopLevelDomain, 'archi', 'ICANN-era Generic - English', 'architects and architect firms[47]' ),
( @activeTopLevelDomain, 'army', 'ICANN-era Generic - English', 'defense contractors' ),
( @activeTopLevelDomain, 'art', 'ICANN-era Generic - English', 'artists, museums, art galleries, dealers, service providers and contractors' ),
( @activeTopLevelDomain, 'associates', 'ICANN-era Generic - English', 'business associations' ),
( @activeTopLevelDomain, 'attorney', 'ICANN-era Generic - English', 'attorneys and legal organizations' ),
( @activeTopLevelDomain, 'auction', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'audible', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'audio', 'ICANN-era Generic - English', 'stereo/sound systems, music' ),
( @activeTopLevelDomain, 'author', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'auto', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'autos', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'aws', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'baby', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'bananarepublic', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'band', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'bar', 'ICANN-era Generic - English', 'Bars and related industry' ),
( @activeTopLevelDomain, 'barefoot', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'bargains', 'ICANN-era Generic - English', 'coupons and online sellers' ),
( @activeTopLevelDomain, 'baseball', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'basketball', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'beauty', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'beer', 'ICANN-era Generic - English', 'breweries and beer aficionados' ),
( @activeTopLevelDomain, 'best', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'bestbuy', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'bet', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'bible', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'bid', 'ICANN-era Generic - English', 'auctions' ),
( @activeTopLevelDomain, 'bike', 'ICANN-era Generic - English', 'bicycles' ),
( @activeTopLevelDomain, 'bingo', 'ICANN-era Generic - English', 'bingo' ),
( @activeTopLevelDomain, 'bio', 'ICANN-era Generic - English', 'biodiversity, biographies' ),
( @activeTopLevelDomain, 'biz', 'ICANN-era Generic - English', 'business' ),
( @activeTopLevelDomain, 'black', 'ICANN-era Generic - English', 'those who like the color black[52]' ),
( @activeTopLevelDomain, 'blackfriday', 'ICANN-era Generic - English', 'Black Friday, retail' ),
( @activeTopLevelDomain, 'blockbuster', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'blog', 'ICANN-era Generic - English', 'Blogs' ),
( @activeTopLevelDomain, 'blue', 'ICANN-era Generic - English', 'those who like the color blue[54]' ),
( @activeTopLevelDomain, 'boo', 'ICANN-era Generic - English', 'ghosts and spooky business' ),
( @activeTopLevelDomain, 'book', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'boots', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'bot', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'boutique', 'ICANN-era Generic - English', 'specialized businesses' ),
( @activeTopLevelDomain, 'box', 'ICANN-era Generic - English', 'individuals and businesses, in order to promote personal cloud storage' ),
( @activeTopLevelDomain, 'broadway', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'broker', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'build', 'ICANN-era Generic - English', 'construction industry' ),
( @activeTopLevelDomain, 'builders', 'ICANN-era Generic - English', 'construction workers' ),
( @activeTopLevelDomain, 'business', 'ICANN-era Generic - English', 'businesses' ),
( @activeTopLevelDomain, 'buy', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'buzz', 'ICANN-era Generic - English', 'marketing and social networking' ),
( @activeTopLevelDomain, 'cab', 'ICANN-era Generic - English', 'cabs and taxi companies' ),
( @activeTopLevelDomain, 'cafe', 'ICANN-era Generic - English', 'coffee industry' ),
( @activeTopLevelDomain, 'call', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'cam', 'ICANN-era Generic - English', 'entertainment[56]' ),
( @activeTopLevelDomain, 'camera', 'ICANN-era Generic - English', 'camera-related businesses' ),
( @activeTopLevelDomain, 'camp', 'ICANN-era Generic - English', 'camps and camping' ),
( @activeTopLevelDomain, 'cancerresearch', 'ICANN-era Generic - English', 'Organizations, research institutes and individuals interested in ending cancer through research [58]' ),
( @activeTopLevelDomain, 'capital', 'ICANN-era Generic - English', 'financial firms' ),
( @activeTopLevelDomain, 'car', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'cards', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'care', 'ICANN-era Generic - English', 'healthcare industry' ),
( @activeTopLevelDomain, 'career', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'careers', 'ICANN-era Generic - English', 'Employment' ),
( @activeTopLevelDomain, 'cars', 'ICANN-era Generic - English', 'Automotive' ),
( @activeTopLevelDomain, 'case', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'cash', 'ICANN-era Generic - English', 'financial' ),
( @activeTopLevelDomain, 'casino', 'ICANN-era Generic - English', 'casinos' ),
( @activeTopLevelDomain, 'catering', 'ICANN-era Generic - English', 'Food service' ),
( @activeTopLevelDomain, 'catholic', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'center', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'ceo', 'ICANN-era Generic - English', 'CEOs' ),
( @activeTopLevelDomain, 'cfd', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'channel', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'chat', 'ICANN-era Generic - English', 'online chat' ),
( @activeTopLevelDomain, 'cheap', 'ICANN-era Generic - English', 'Resellers' ),
( @activeTopLevelDomain, 'christmas', 'ICANN-era Generic - English', 'Christmas' ),
( @activeTopLevelDomain, 'church', 'ICANN-era Generic - English', 'churches' ),
( @activeTopLevelDomain, 'cipriani', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'circle', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'city', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'claims', 'ICANN-era Generic - English', 'retail, auctions' ),
( @activeTopLevelDomain, 'cleaning', 'ICANN-era Generic - English', 'Cleaning services' ),
( @activeTopLevelDomain, 'click', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'clinic', 'ICANN-era Generic - English', 'healthcare clinics' ),
( @activeTopLevelDomain, 'clothing', 'ICANN-era Generic - English', 'Apparel' ),
( @activeTopLevelDomain, 'cloud', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'club', 'ICANN-era Generic - English', 'groups, organizations, assemblies, communities, general' ),
( @activeTopLevelDomain, 'coach', 'ICANN-era Generic - English', 'travel (flights and motor coaches)' ),
( @activeTopLevelDomain, 'codes', 'ICANN-era Generic - English', 'computer and/or encryption code enthusiasts' ),
( @activeTopLevelDomain, 'coffee', 'ICANN-era Generic - English', 'cafés and coffee aficionados' ),
( @activeTopLevelDomain, 'college', 'ICANN-era Generic - English', 'Educational' ),
( @activeTopLevelDomain, 'community', 'ICANN-era Generic - English', 'social groups, neighborhoods' ),
( @activeTopLevelDomain, 'company', 'ICANN-era Generic - English', 'business associations' ),
( @activeTopLevelDomain, 'compare', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'computer', 'ICANN-era Generic - English', 'Technology' ),
( @activeTopLevelDomain, 'condos', 'ICANN-era Generic - English', 'Real estate' ),
( @activeTopLevelDomain, 'construction', 'ICANN-era Generic - English', 'Construction industry' ),
( @activeTopLevelDomain, 'consulting', 'ICANN-era Generic - English', 'hired advisors' ),
( @activeTopLevelDomain, 'contact', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'contractors', 'ICANN-era Generic - English', 'Remodeling and independent businesses' ),
( @activeTopLevelDomain, 'cooking', 'ICANN-era Generic - English', 'sharing recipes' ),
( @activeTopLevelDomain, 'cool', 'ICANN-era Generic - English', 'General interests' ),
( @activeTopLevelDomain, 'coop', 'ICANN-era Generic - English', 'cooperatives' ),
( @activeTopLevelDomain, 'country', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'coupon', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'coupons', 'ICANN-era Generic - English', 'coupons' ),
( @activeTopLevelDomain, 'courses', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'credit', 'ICANN-era Generic - English', 'Financial institutions' ),
( @activeTopLevelDomain, 'creditcard', 'ICANN-era Generic - English', 'Financial institutions' ),
( @activeTopLevelDomain, 'cruise', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'cricket', 'ICANN-era Generic - English', 'cricket' ),
( @activeTopLevelDomain, 'cruises', 'ICANN-era Generic - English', 'cruise businesses and travel' ),
( @activeTopLevelDomain, 'dad', 'ICANN-era Generic - English', 'families' ),
( @activeTopLevelDomain, 'dance', 'ICANN-era Generic - English', 'Dance studios and companies' ),
( @activeTopLevelDomain, 'data', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'date', 'ICANN-era Generic - English', 'online dating' ),
( @activeTopLevelDomain, 'dating', 'ICANN-era Generic - English', 'online dating' ),
( @activeTopLevelDomain, 'day', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'deal', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'deals', 'ICANN-era Generic - English', 'online shopping and couponing' ),
( @activeTopLevelDomain, 'degree', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'delivery', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'democrat', 'ICANN-era Generic - English', 'Democratic Party politics' ),
( @activeTopLevelDomain, 'dental', 'ICANN-era Generic - English', 'dentists' ),
( @activeTopLevelDomain, 'dentist', 'ICANN-era Generic - English', 'dentists' ),
( @activeTopLevelDomain, 'design', 'ICANN-era Generic - English', 'graphic art and fashion' ),
( @activeTopLevelDomain, 'dev', 'ICANN-era Generic - English', 'development' ),
( @activeTopLevelDomain, 'diamonds', 'ICANN-era Generic - English', 'diamond and jewelry industry' ),
( @activeTopLevelDomain, 'diet', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'digital', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'direct', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'directory', 'ICANN-era Generic - English', 'general directory' ),
( @activeTopLevelDomain, 'discount', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'diy', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'docs', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'doctor', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'dog', 'ICANN-era Generic - English', 'dog stores and owners' ),
( @activeTopLevelDomain, 'domains', 'ICANN-era Generic - English', 'domain registries' ),
( @activeTopLevelDomain, 'dot', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'download', 'ICANN-era Generic - English', 'technology' ),
( @activeTopLevelDomain, 'drive', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'duck', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'earth', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'eat', 'ICANN-era Generic - English', 'restaurants and foodies' ),
( @activeTopLevelDomain, 'eco', 'ICANN-era Generic - English', 'Sustainability minded companies, non-profits and professionals.[62]' ),
( @activeTopLevelDomain, 'education', 'ICANN-era Generic - English', 'educational institutes' ),
( @activeTopLevelDomain, 'email', 'ICANN-era Generic - English', 'email' ),
( @activeTopLevelDomain, 'energy', 'ICANN-era Generic - English', 'energy industry and marketing' ),
( @activeTopLevelDomain, 'engineer', 'ICANN-era Generic - English', 'engineers and engineering firms' ),
( @activeTopLevelDomain, 'engineering', 'ICANN-era Generic - English', 'engineering firms' ),
( @activeTopLevelDomain, 'equipment', 'ICANN-era Generic - English', 'equipment-related businesses' ),
( @activeTopLevelDomain, 'esq', 'ICANN-era Generic - English', 'lawyers, law firms, legal professionals' ),
( @activeTopLevelDomain, 'estate', 'ICANN-era Generic - English', 'real estate businesses' ),
( @activeTopLevelDomain, 'events', 'ICANN-era Generic - English', 'happenings' ),
( @activeTopLevelDomain, 'exchange', 'ICANN-era Generic - English', 'generic trade' ),
( @activeTopLevelDomain, 'expert', 'ICANN-era Generic - English', 'generic expertise' ),
( @activeTopLevelDomain, 'exposed', 'ICANN-era Generic - English', 'general interest' ),
( @activeTopLevelDomain, 'express', 'ICANN-era Generic - English', 'shipping' ),
( @activeTopLevelDomain, 'fail', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'faith', 'ICANN-era Generic - English', 'religion and churches' ),
( @activeTopLevelDomain, 'family', 'ICANN-era Generic - English', 'families' ),
( @activeTopLevelDomain, 'fan', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'fans', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'farm', 'ICANN-era Generic - English', 'farms and agriculture' ),
( @activeTopLevelDomain, 'fashion', 'ICANN-era Generic - English', 'clothing industry' ),
( @activeTopLevelDomain, 'fast', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'feedback', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'film', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'final', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'finance', 'ICANN-era Generic - English', 'financial' ),
( @activeTopLevelDomain, 'financial', 'ICANN-era Generic - English', 'financial' ),
( @activeTopLevelDomain, 'fire', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'fish', 'ICANN-era Generic - English', 'fishing businesses, sports, and interests' ),
( @activeTopLevelDomain, 'fishing', 'ICANN-era Generic - English', 'fishing businesses, sports, and interests' ),
( @activeTopLevelDomain, 'fit', 'ICANN-era Generic - English', 'Fitness and exercise' ),
( @activeTopLevelDomain, 'fitness', 'ICANN-era Generic - English', 'Fitness and exercise' ),
( @activeTopLevelDomain, 'flights', 'ICANN-era Generic - English', 'airline businesses and travel' ),
( @activeTopLevelDomain, 'florist', 'ICANN-era Generic - English', 'florists' ),
( @activeTopLevelDomain, 'flowers', 'ICANN-era Generic - English', 'florists and gardens' ),
( @activeTopLevelDomain, 'fly', 'ICANN-era Generic - English', 'travel' ),
( @activeTopLevelDomain, 'foo', 'ICANN-era Generic - English', 'web development' ),
( @activeTopLevelDomain, 'food', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'foodnetwork', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'football', 'ICANN-era Generic - English', 'soccer and American football' ),
( @activeTopLevelDomain, 'forsale', 'ICANN-era Generic - English', 'online retail' ),
( @activeTopLevelDomain, 'forum', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'foundation', 'ICANN-era Generic - English', 'charitable organizations' ),
( @activeTopLevelDomain, 'free', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'frontdoor', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'fun', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'fund', 'ICANN-era Generic - English', 'financial' ),
( @activeTopLevelDomain, 'furniture', 'ICANN-era Generic - English', 'furniture businesses' ),
( @activeTopLevelDomain, 'fyi', 'ICANN-era Generic - English', '"for your information"' ),
( @activeTopLevelDomain, 'gallery', 'ICANN-era Generic - English', 'photo and art galleries' ),
( @activeTopLevelDomain, 'game', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'games', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'garden', 'ICANN-era Generic - English', 'gardening' ),
( @activeTopLevelDomain, 'gift', 'ICANN-era Generic - English', 'gift-giving' ),
( @activeTopLevelDomain, 'gifts', 'ICANN-era Generic - English', 'gift-giving' ),
( @activeTopLevelDomain, 'gives', 'ICANN-era Generic - English', 'charities and gift-giving' ),
( @activeTopLevelDomain, 'glass', 'ICANN-era Generic - English', 'window sales and repairs' ),
( @activeTopLevelDomain, 'global', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'gold', 'ICANN-era Generic - English', 'gold and luxury' ),
( @activeTopLevelDomain, 'golf', 'ICANN-era Generic - English', 'golf' ),
( @activeTopLevelDomain, 'gop', 'ICANN-era Generic - English', 'Republican Party politics' ),
( @activeTopLevelDomain, 'graphics', 'ICANN-era Generic - English', 'graphics' ),
( @activeTopLevelDomain, 'green', 'ICANN-era Generic - English', 'the environmentally-focused' ),
( @activeTopLevelDomain, 'gripe', 'ICANN-era Generic - English', 'opinion sites' ),
( @activeTopLevelDomain, 'grocery', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'group', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'guide', 'ICANN-era Generic - English', 'help sites' ),
( @activeTopLevelDomain, 'guitars', 'ICANN-era Generic - English', 'Guitars' ),
( @activeTopLevelDomain, 'guru', 'ICANN-era Generic - English', 'generic expertise' ),
( @activeTopLevelDomain, 'hair', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'hangout', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'health', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'healthcare', 'ICANN-era Generic - English', 'healthcare industry' ),
( @activeTopLevelDomain, 'help', 'ICANN-era Generic - English', 'help sites' ),
( @activeTopLevelDomain, 'here', 'ICANN-era Generic - English', 'generic geographic' ),
( @activeTopLevelDomain, 'hiphop', 'ICANN-era Generic - English', 'Hip hop culture' ),
( @activeTopLevelDomain, 'hiv', 'ICANN-era Generic - English', 'AIDS and HIV' ),
( @activeTopLevelDomain, 'hockey', 'ICANN-era Generic - English', 'hockey' ),
( @activeTopLevelDomain, 'holdings', 'ICANN-era Generic - English', 'real estate or financial business' ),
( @activeTopLevelDomain, 'holiday', 'ICANN-era Generic - English', 'holiday gift industry' ),
( @activeTopLevelDomain, 'homegoods', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'homes', 'ICANN-era Generic - English', 'real estate professionals' ),
( @activeTopLevelDomain, 'homesense', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'horse', 'ICANN-era Generic - English', 'horse-related businesses and interest' ),
( @activeTopLevelDomain, 'hospital', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'host', 'ICANN-era Generic - English', 'network companies' ),
( @activeTopLevelDomain, 'hosting', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'hot', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'hotels', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'house', 'ICANN-era Generic - English', 'real estate and construction businesses' ),
( @activeTopLevelDomain, 'how', 'ICANN-era Generic - English', 'how-to guides' ),
( @activeTopLevelDomain, 'ice', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'info', 'ICANN-era Generic - English', 'information' ),
( @activeTopLevelDomain, 'ing', 'ICANN-era Generic - English', 'Verbal suffix: e.g., "jump.ing".' ),
( @activeTopLevelDomain, 'ink', 'ICANN-era Generic - English', 'creative printing or tattooing[71]' ),
( @activeTopLevelDomain, 'institute', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'insurance', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'insure', 'ICANN-era Generic - English', 'Insurance companies' ),
( @activeTopLevelDomain, 'international', 'ICANN-era Generic - English', 'international entities' ),
( @activeTopLevelDomain, 'investments', 'ICANN-era Generic - English', 'financial' ),
( @activeTopLevelDomain, 'jewelry', 'ICANN-era Generic - English', 'jewelry stores' ),
( @activeTopLevelDomain, 'jobs', 'ICANN-era Generic - English', 'Employment' ),
( @activeTopLevelDomain, 'joy', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'kim', 'ICANN-era Generic - English', 'people named Kim' ),
( @activeTopLevelDomain, 'kitchen', 'ICANN-era Generic - English', 'food industry and remodeling' ),
( @activeTopLevelDomain, 'land', 'ICANN-era Generic - English', 'real estate' ),
( @activeTopLevelDomain, 'latino', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'law', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'lawyer', 'ICANN-era Generic - English', 'lawyers and legal organizations' ),
( @activeTopLevelDomain, 'lease', 'ICANN-era Generic - English', 'financing' ),
( @activeTopLevelDomain, 'legal', 'ICANN-era Generic - English', 'lawyers and legal organizations' ),
( @activeTopLevelDomain, 'lgbt', 'ICANN-era Generic - English', 'the lesbian, gay, bisexual and transgender community' ),
( @activeTopLevelDomain, 'life', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'lifeinsurance', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'lighting', 'ICANN-era Generic - English', 'lighting' ),
( @activeTopLevelDomain, 'like', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'limited', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'limo', 'ICANN-era Generic - English', 'limousine businesses' ),
( @activeTopLevelDomain, 'link', 'ICANN-era Generic - English', 'connecting to information[75]' ),
( @activeTopLevelDomain, 'live', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'living', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'loan', 'ICANN-era Generic - English', 'banks and lenders' ),
( @activeTopLevelDomain, 'loans', 'ICANN-era Generic - English', 'banks and lenders' ),
( @activeTopLevelDomain, 'locker', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'lol', 'ICANN-era Generic - English', 'LOL: laughing out loud' ),
( @activeTopLevelDomain, 'lotto', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'love', 'ICANN-era Generic - English', 'dating sites' ),
( @activeTopLevelDomain, 'luxury', 'ICANN-era Generic - English', 'businesses catering to the wealthy' ),
( @activeTopLevelDomain, 'makeup', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'management', 'ICANN-era Generic - English', 'business management' ),
( @activeTopLevelDomain, 'map', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'market', 'ICANN-era Generic - English', 'marketing services and retailers' ),
( @activeTopLevelDomain, 'marketing', 'ICANN-era Generic - English', 'marketing services' ),
( @activeTopLevelDomain, 'markets', 'ICANN-era Generic - English', 'financial and stock markets' ),
( @activeTopLevelDomain, 'mba', 'ICANN-era Generic - English', 'Masters in Business Administration' ),
( @activeTopLevelDomain, 'med', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'media', 'ICANN-era Generic - English', 'general media interests' ),
( @activeTopLevelDomain, 'meet', 'ICANN-era Generic - English', 'social gatherings, meeting new people' ),
( @activeTopLevelDomain, 'meme', 'ICANN-era Generic - English', 'Internet memes' ),
( @activeTopLevelDomain, 'memorial', 'ICANN-era Generic - English', 'memorial sites' ),
( @activeTopLevelDomain, 'men', 'ICANN-era Generic - English', 'men' ),
( @activeTopLevelDomain, 'menu', 'ICANN-era Generic - English', 'restaurants' ),
( @activeTopLevelDomain, 'mint', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'mobi', 'ICANN-era Generic - English', 'mobile devices' ),
( @activeTopLevelDomain, 'mobile', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'mobily', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'moe', 'ICANN-era Generic - English', 'Japanese otaku culture; see moe (slang)' ),
( @activeTopLevelDomain, 'mom', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'money', 'ICANN-era Generic - English', 'financial' ),
( @activeTopLevelDomain, 'mortgage', 'ICANN-era Generic - English', 'mortgage lenders' ),
( @activeTopLevelDomain, 'motorcycles', 'ICANN-era Generic - English', 'motorcycles' ),
( @activeTopLevelDomain, 'mov', 'ICANN-era Generic - English', 'Digital video' ),
( @activeTopLevelDomain, 'movie', 'ICANN-era Generic - English', 'movies and cinemas' ),
( @activeTopLevelDomain, 'museum', 'ICANN-era Generic - English', 'museums' ),
( @activeTopLevelDomain, 'name', 'ICANN-era Generic - English', 'individuals, by name' ),
( @activeTopLevelDomain, 'navy', 'ICANN-era Generic - English', 'defense contractors' ),
( @activeTopLevelDomain, 'network', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'new', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'news', 'ICANN-era Generic - English', 'news sites' ),
( @activeTopLevelDomain, 'ngo', 'ICANN-era Generic - English', 'Non-governmental organizations.' ),
( @activeTopLevelDomain, 'ninja', 'ICANN-era Generic - English', 'general expertise' ),
( @activeTopLevelDomain, 'now', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'observer', 'ICANN-era Generic - English', 'news organizations' ),
( @activeTopLevelDomain, 'off', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'one', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'ong', 'ICANN-era Generic - English', 'Non-governmental organizations.' ),
( @activeTopLevelDomain, 'onl', 'ICANN-era Generic - English', 'short for "online"' ),
( @activeTopLevelDomain, 'online', 'ICANN-era Generic - English', 'generic' ),
( @activeTopLevelDomain, 'ooo', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'open', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'organic', 'ICANN-era Generic - English', 'organic gardeners, farmers, foods, etc.' )
;

  INSERT INTO @DataLoadTopLevelDomain ( RowStatus, TopLevelDomain, TopLevelDomainType, TopLevelDomainDescription )
  VALUES
( @activeTopLevelDomain, 'origins', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'page', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'partners', 'ICANN-era Generic - English', 'businesses' ),
( @activeTopLevelDomain, 'parts', 'ICANN-era Generic - English', 'manufacturing and consumer auto' ),
( @activeTopLevelDomain, 'party', 'ICANN-era Generic - English', 'nightclubs and social gatherings' ),
( @activeTopLevelDomain, 'pay', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'pet', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'pharmacy', 'ICANN-era Generic - English', 'pharmacies' ),
( @activeTopLevelDomain, 'phone', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'photo', 'ICANN-era Generic - English', 'photography and photo-sharing' ),
( @activeTopLevelDomain, 'photography', 'ICANN-era Generic - English', 'photography and photo-sharing' ),
( @activeTopLevelDomain, 'photos', 'ICANN-era Generic - English', 'photography and photo-sharing' ),
( @activeTopLevelDomain, 'physio', 'ICANN-era Generic - English', 'physical therapists' ),
( @activeTopLevelDomain, 'pics', 'ICANN-era Generic - English', 'photography and photo-sharing' ),
( @activeTopLevelDomain, 'pictures', 'ICANN-era Generic - English', 'photography and photo-sharing' ),
( @activeTopLevelDomain, 'pid', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'pin', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'pink', 'ICANN-era Generic - English', 'those who like the color pink' ),
( @activeTopLevelDomain, 'pizza', 'ICANN-era Generic - English', 'pizza parlors' ),
( @activeTopLevelDomain, 'place', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'plumbing', 'ICANN-era Generic - English', 'plumbing businesses' ),
( @activeTopLevelDomain, 'plus', 'ICANN-era Generic - English', 'generic' ),
( @activeTopLevelDomain, 'poker', 'ICANN-era Generic - English', 'Poker players and sites' ),
( @activeTopLevelDomain, 'porn', 'ICANN-era Generic - English', 'adult entertainment (pornography)' ),
( @activeTopLevelDomain, 'post', 'ICANN-era Generic - English', 'postal services' ),
( @activeTopLevelDomain, 'press', 'ICANN-era Generic - English', 'publishing and journalism' ),
( @activeTopLevelDomain, 'prime', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'pro', 'ICANN-era Generic - English', 'professions/professionals' ),
( @activeTopLevelDomain, 'productions', 'ICANN-era Generic - English', 'studio/art businesses' ),
( @activeTopLevelDomain, 'prof', 'ICANN-era Generic - English', 'Professors, teachers and learning' ),
( @activeTopLevelDomain, 'promo', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'properties', 'ICANN-era Generic - English', 'real estate' ),
( @activeTopLevelDomain, 'property', 'ICANN-era Generic - English', 'real estate' ),
( @activeTopLevelDomain, 'protection', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'qpon', 'ICANN-era Generic - English', 'coupons' ),
( @activeTopLevelDomain, 'racing', 'ICANN-era Generic - English', 'racing' ),
( @activeTopLevelDomain, 'radio', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'read', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'realestate', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'realty', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'recipes', 'ICANN-era Generic - English', 'recipes and cooking' ),
( @activeTopLevelDomain, 'red', 'ICANN-era Generic - English', 'those who like the color red[83]' ),
( @activeTopLevelDomain, 'rehab', 'ICANN-era Generic - English', 'Rehab centers and support sites' ),
( @activeTopLevelDomain, 'ren', 'ICANN-era Generic - English', 'Renren users (ren means "people/person" in Mandarin Chinese pinyin' ),
( @activeTopLevelDomain, 'rent', 'ICANN-era Generic - English', 'Real estate professionals and small businesses' ),
( @activeTopLevelDomain, 'rentals', 'ICANN-era Generic - English', 'short-term ownership' ),
( @activeTopLevelDomain, 'repair', 'ICANN-era Generic - English', 'general repair/maintenance businesses' ),
( @activeTopLevelDomain, 'report', 'ICANN-era Generic - English', 'business services' ),
( @activeTopLevelDomain, 'republican', 'ICANN-era Generic - English', 'Republican Party politics' ),
( @activeTopLevelDomain, 'rest', 'ICANN-era Generic - English', 'Restaurants and related industry' ),
( @activeTopLevelDomain, 'review', 'ICANN-era Generic - English', 'public reviews' ),
( @activeTopLevelDomain, 'reviews', 'ICANN-era Generic - English', 'public reviews' ),
( @activeTopLevelDomain, 'rich', 'ICANN-era Generic - English', 'businesses catering to the wealthy' ),
( @activeTopLevelDomain, 'rip', 'ICANN-era Generic - English', 'memorial sites[85]' ),
( @activeTopLevelDomain, 'rocks', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'rodeo', 'ICANN-era Generic - English', 'Rodeo interest' ),
( @activeTopLevelDomain, 'room', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'rugby', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'run', 'ICANN-era Generic - English', 'running and jogging' ),
( @activeTopLevelDomain, 'safe', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'sale', 'ICANN-era Generic - English', 'retail' ),
( @activeTopLevelDomain, 'save', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'scholarships', 'ICANN-era Generic - English', 'scholarship related' ),
( @activeTopLevelDomain, 'school', 'ICANN-era Generic - English', 'schools' ),
( @activeTopLevelDomain, 'science', 'ICANN-era Generic - English', 'science-related sites' ),
( @activeTopLevelDomain, 'search', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'secure', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'security', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'select', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'services', 'ICANN-era Generic - English', 'business services' ),
( @activeTopLevelDomain, 'sex', 'ICANN-era Generic - English', 'adult entertainment (pornography)' ),
( @activeTopLevelDomain, 'sexy', 'ICANN-era Generic - English', 'adult entertainment' ),
( @activeTopLevelDomain, 'shoes', 'ICANN-era Generic - English', 'shoes' ),
( @activeTopLevelDomain, 'shop', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'shopping', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'show', 'ICANN-era Generic - English', 'entertainment and vlogs' ),
( @activeTopLevelDomain, 'showtime', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'silk', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'singles', 'ICANN-era Generic - English', 'online dating' ),
( @activeTopLevelDomain, 'site', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'ski', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'skin', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'sky', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'sling', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'smile', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'soccer', 'ICANN-era Generic - English', 'soccer' ),
( @activeTopLevelDomain, 'social', 'ICANN-era Generic - English', 'general interest' ),
( @activeTopLevelDomain, 'software', 'ICANN-era Generic - English', 'computer software' ),
( @activeTopLevelDomain, 'solar', 'ICANN-era Generic - English', 'solar-power' ),
( @activeTopLevelDomain, 'solutions', 'ICANN-era Generic - English', 'business services' ),
( @activeTopLevelDomain, 'song', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'space', 'ICANN-era Generic - English', 'as a creative space' ),
( @activeTopLevelDomain, 'spot', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'spreadbetting', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'storage', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'store', 'ICANN-era Generic - English', 'stores' ),
( @activeTopLevelDomain, 'stream', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'studio', 'ICANN-era Generic - English', 'art, fitness, & entertainment' ),
( @activeTopLevelDomain, 'study', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'style', 'ICANN-era Generic - English', 'fashion' ),
( @activeTopLevelDomain, 'sucks', 'ICANN-era Generic - English', 'gripe sites' ),
( @activeTopLevelDomain, 'supplies', 'ICANN-era Generic - English', 'manufacturing industries' ),
( @activeTopLevelDomain, 'supply', 'ICANN-era Generic - English', 'manufacturing industries' ),
( @activeTopLevelDomain, 'support', 'ICANN-era Generic - English', 'help pages' ),
( @activeTopLevelDomain, 'surf', 'ICANN-era Generic - English', 'surfing' ),
( @activeTopLevelDomain, 'surgery', 'ICANN-era Generic - English', 'healthcare industry' ),
( @activeTopLevelDomain, 'systems', 'ICANN-era Generic - English', 'technology' ),
( @activeTopLevelDomain, 'talk', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'tattoo', 'ICANN-era Generic - English', 'tattoo aficionados' ),
( @activeTopLevelDomain, 'tax', 'ICANN-era Generic - English', 'financial' ),
( @activeTopLevelDomain, 'taxi', 'ICANN-era Generic - English', 'taxi services' ),
( @activeTopLevelDomain, 'team', 'ICANN-era Generic - English', 'team sports' ),
( @activeTopLevelDomain, 'tech', 'ICANN-era Generic - English', 'technology' ),
( @activeTopLevelDomain, 'technology', 'ICANN-era Generic - English', 'technology' ),
( @activeTopLevelDomain, 'tel', 'ICANN-era Generic - English', 'Internet communication services' ),
( @activeTopLevelDomain, 'tennis', 'ICANN-era Generic - English', 'tennis' ),
( @activeTopLevelDomain, 'theater', 'ICANN-era Generic - English', 'theaters and cinemas' ),
( @activeTopLevelDomain, 'theatre', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'tickets', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'tips', 'ICANN-era Generic - English', 'general help topics' ),
( @activeTopLevelDomain, 'tires', 'ICANN-era Generic - English', 'tire manufacturers' ),
( @activeTopLevelDomain, 'today', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'tools', 'ICANN-era Generic - English', 'manufacturing industries' ),
( @activeTopLevelDomain, 'top', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'tours', 'ICANN-era Generic - English', 'tourism' ),
( @activeTopLevelDomain, 'town', 'ICANN-era Generic - English', 'generic geographic' ),
( @activeTopLevelDomain, 'toys', 'ICANN-era Generic - English', 'toy businesses' ),
( @activeTopLevelDomain, 'trade', 'ICANN-era Generic - English', 'businesses' ),
( @activeTopLevelDomain, 'trading', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'training', 'ICANN-era Generic - English', 'training and how-tos' ),
( @activeTopLevelDomain, 'travel', 'ICANN-era Generic - English', 'travel and tourism industry related sites' ),
( @activeTopLevelDomain, 'travelersinsurance', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'trust', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'tube', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'tunes', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'uconnect', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'university', 'ICANN-era Generic - English', 'young adults, university life' ),
( @activeTopLevelDomain, 'vacations', 'ICANN-era Generic - English', 'travel' ),
( @activeTopLevelDomain, 'vet', 'ICANN-era Generic - English', 'veterans and veterinarians' ),
( @activeTopLevelDomain, 'video', 'ICANN-era Generic - English', 'video sharing' ),
( @activeTopLevelDomain, 'villas', 'ICANN-era Generic - English', 'real estate and/or travel businesses' ),
( @activeTopLevelDomain, 'vip', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'vision', 'ICANN-era Generic - English', 'eye-care businesses' ),
( @activeTopLevelDomain, 'vodka', 'ICANN-era Generic - English', 'Vodka-related businesses and interest' ),
( @activeTopLevelDomain, 'vote', 'ICANN-era Generic - English', 'democratic elections and campaign websites' ),
( @activeTopLevelDomain, 'voting', 'ICANN-era Generic - English', 'polling sites' ),
( @activeTopLevelDomain, 'voyage', 'ICANN-era Generic - English', 'travel' ),
( @activeTopLevelDomain, 'wang', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'watch', 'ICANN-era Generic - English', 'Watches' ),
( @activeTopLevelDomain, 'watches', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'weather', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'webcam', 'ICANN-era Generic - English', 'Web cam shows and video sharing' ),
( @activeTopLevelDomain, 'website', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'wed', 'ICANN-era Generic - English', 'engaged couples and wedding-oriented businesses' ),
( @activeTopLevelDomain, 'wedding', 'ICANN-era Generic - English', 'wedding-oriented businesses' ),
( @activeTopLevelDomain, 'whoswho', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'wiki', 'ICANN-era Generic - English', 'wikis' ),
( @activeTopLevelDomain, 'win', 'ICANN-era Generic - English', 'games, Microsoft Windows' ),
( @activeTopLevelDomain, 'wine', 'ICANN-era Generic - English', 'Wine' ),
( @activeTopLevelDomain, 'winners', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'work', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'works', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'world', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'wow', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'wtf', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'xxx', 'ICANN-era Generic - English', 'adult entertainment (pornography)' ),
( @activeTopLevelDomain, 'xyz', 'ICANN-era Generic - English', 'general' ),
( @activeTopLevelDomain, 'yachts', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'yoga', 'ICANN-era Generic - English', 'yoga' ),
( @activeTopLevelDomain, 'you', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'zero', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'zone', 'ICANN-era Generic - English', NULL ),
( @activeTopLevelDomain, 'shouji', 'ICANN-era Generic - Chinese', 'phone' ),
( @activeTopLevelDomain, 'tushu', 'ICANN-era Generic - Chinese', 'books' ),
( @activeTopLevelDomain, 'wanggou', 'ICANN-era Generic - Chinese', 'online shopping' ),
( @activeTopLevelDomain, 'weibo', 'ICANN-era Generic - Chinese', 'microblogging' ),
( @activeTopLevelDomain, 'xihuan', 'ICANN-era Generic - Chinese', NULL ),
( @activeTopLevelDomain, 'arte', 'ICANN-era Generic - French', NULL ),
( @activeTopLevelDomain, 'clinique', 'ICANN-era Generic - French', NULL ),
( @activeTopLevelDomain, 'luxe', 'ICANN-era Generic - French', NULL ),
( @activeTopLevelDomain, 'maison', 'ICANN-era Generic - French', '"house"' ),
( @activeTopLevelDomain, 'moi', 'ICANN-era Generic - French', NULL ),
( @activeTopLevelDomain, 'rsvp', 'ICANN-era Generic - French', 'Invitations and replies' ),
( @activeTopLevelDomain, 'sarl', 'ICANN-era Generic - French', NULL ),
( @activeTopLevelDomain, 'epost', 'ICANN-era Generic - German', 'e-mail' ),
( @activeTopLevelDomain, 'gmbh', 'ICANN-era Generic - German', 'GmbH' ),
( @activeTopLevelDomain, 'haus', 'ICANN-era Generic - German', '"house"' ),
( @activeTopLevelDomain, 'immobilien', 'ICANN-era Generic - German', '"real estate"' ),
( @activeTopLevelDomain, 'jetzt', 'ICANN-era Generic - German', '"now"' ),
( @activeTopLevelDomain, 'kaufen', 'ICANN-era Generic - German', '"buy"' ),
( @activeTopLevelDomain, 'kinder', 'ICANN-era Generic - German', 'children' ),
( @activeTopLevelDomain, 'reise', 'ICANN-era Generic - German', '"travel"' ),
( @activeTopLevelDomain, 'reisen', 'ICANN-era Generic - German', '"traveling"' ),
( @activeTopLevelDomain, 'schule', 'ICANN-era Generic - German', '"school"' ),
( @activeTopLevelDomain, 'versicherung', 'ICANN-era Generic - German', NULL ),
( @activeTopLevelDomain, 'desi', 'ICANN-era Generic - Hindi', 'Hindi for the peoples and cultures of South Asia' ),
( @activeTopLevelDomain, 'shiksha', 'ICANN-era Generic - Hindi', NULL ),
( @activeTopLevelDomain, 'casa', 'ICANN-era Generic - Italian', '"house"' ),
( @activeTopLevelDomain, 'immo', 'ICANN-era Generic - Italian', 'French, German,[98] and Italian abbreviation for "real estate"' ),
( @activeTopLevelDomain, 'moda', 'ICANN-era Generic - Italian', '"fashion"' ),
( @activeTopLevelDomain, 'voto', 'ICANN-era Generic - Italian', NULL ),
( @activeTopLevelDomain, 'bom', 'ICANN-era Generic - Portuguese', 'good' ),
( @activeTopLevelDomain, 'passagens', 'ICANN-era Generic - Portuguese', NULL ),
( @activeTopLevelDomain, 'abogado', 'ICANN-era Generic - Spanish', '"lawyer"' ),
( @activeTopLevelDomain, 'gratis', 'ICANN-era Generic - Spanish', '"free"' ),
( @activeTopLevelDomain, 'futbol', 'ICANN-era Generic - Spanish', 'soccer' ),
( @activeTopLevelDomain, 'hoteles', 'ICANN-era Generic - Spanish', 'hotels' ),
( @activeTopLevelDomain, 'juegos', 'ICANN-era Generic - Spanish', '"games"' ),
( @activeTopLevelDomain, 'ltda', 'ICANN-era Generic - Spanish', 'companies in South America' ),
( @activeTopLevelDomain, 'soy', 'ICANN-era Generic - Spanish', '"I am"; Also refers to the soybean and its food derivatives' ),
( @activeTopLevelDomain, 'tienda', 'ICANN-era Generic - Spanish', '"shop", "store"' ),
( @activeTopLevelDomain, 'uno', 'ICANN-era Generic - Spanish', '"one", for websites targeting Spanish speaking consumers' ),
( @activeTopLevelDomain, 'viajes', 'ICANN-era Generic - Spanish', '"travel"' ),
( @activeTopLevelDomain, 'vuelos', 'ICANN-era Generic - Spanish', NULL ),
( @activeTopLevelDomain, 'bar', 'Corporate identifiers', 'bars and pubs' ),
( @activeTopLevelDomain, 'bank', 'Corporate identifiers', 'banks' ),
( @activeTopLevelDomain, 'coop', 'Corporate identifiers', 'cooperatives' ),
( @activeTopLevelDomain, 'enterprises', 'Corporate identifiers', 'business associations' ),
( @activeTopLevelDomain, 'industries', 'Corporate identifiers', 'industrial businesses' ),
( @activeTopLevelDomain, 'institute', 'Corporate identifiers', 'established business associations' ),
( @activeTopLevelDomain, 'pharmacy', 'Corporate identifiers', 'pharmacies' ),
( @activeTopLevelDomain, 'pub', 'Corporate identifiers', 'bars and pubs' ),
( @activeTopLevelDomain, 'realtor', 'Corporate identifiers', 'realtors' ),
( @activeTopLevelDomain, 'reit', 'Corporate identifiers', 'real estate investment trusts' ),
( @activeTopLevelDomain, 'rest', 'Corporate identifiers', 'restaurants' ),
( @activeTopLevelDomain, 'restaurant', 'Corporate identifiers', 'restaurants' ),
( @activeTopLevelDomain, 'ventures', 'Corporate identifiers', NULL ),
( @activeTopLevelDomain, 'africa', 'Africa', 'Africa' ),
( @activeTopLevelDomain, 'capetown', 'Africa', 'Cape Town, South Africa' ),
( @activeTopLevelDomain, 'durban', 'Africa', 'Durban, South Africa' ),
( @activeTopLevelDomain, 'joburg', 'Africa', NULL ),
( @activeTopLevelDomain, 'abudhabi', 'Asia', 'Abu Dhabi' ),
( @activeTopLevelDomain, 'arab', 'Asia', 'League of Arab States' ),
( @activeTopLevelDomain, 'asia', 'Asia', 'Asia-Pacific region' ),
( @activeTopLevelDomain, 'doha', 'Asia', 'Doha' ),
( @activeTopLevelDomain, 'dubai', 'Asia', 'Dubai' ),
( @activeTopLevelDomain, 'krd', 'Asia', ' Kurdistan' ),
( @activeTopLevelDomain, 'kyoto', 'Asia', 'Kyoto, Japan' ),
( @activeTopLevelDomain, 'nagoya', 'Asia', 'Nagoya, Japan' ),
( @activeTopLevelDomain, 'okinawa', 'Asia', 'Okinawa, Japan' ),
( @activeTopLevelDomain, 'osaka', 'Asia', 'Osaka, Japan' ),
( @activeTopLevelDomain, 'ryukyu', 'Asia', 'Ryukyu Islands, Japan' ),
( @activeTopLevelDomain, 'taipei', 'Asia', 'Taipei, Taiwan' ),
( @activeTopLevelDomain, 'tatar', 'Asia', 'Tatar peoples and places' ),
( @activeTopLevelDomain, 'tokyo', 'Asia', 'Tokyo, Japan' ),
( @activeTopLevelDomain, 'yokohama', 'Asia', NULL ),
( @activeTopLevelDomain, 'alsace', 'Europe', ' Alsace, France' ),
( @activeTopLevelDomain, 'amsterdam', 'Europe', 'Amsterdam, The Netherlands' ),
( @activeTopLevelDomain, 'bcn', 'Europe', 'Barcelona, Spain' ),
( @activeTopLevelDomain, 'barcelona', 'Europe', 'Barcelona, Spain' ),
( @activeTopLevelDomain, 'bayern', 'Europe', ' Bavaria, Germany' ),
( @activeTopLevelDomain, 'berlin', 'Europe', 'Berlin, Germany' ),
( @activeTopLevelDomain, 'brussels', 'Europe', 'Brussels, Belgium' ),
( @activeTopLevelDomain, 'budapest', 'Europe', 'Budapest, Hungary' ),
( @activeTopLevelDomain, 'bzh', 'Europe', ' Brittany, France ; Breton language and culture' ),
( @activeTopLevelDomain, 'cat', 'Europe', ' Catalonia; Catalan language and culture' ),
( @activeTopLevelDomain, 'cologne', 'Europe', 'Cologne, Germany' ),
( @activeTopLevelDomain, 'corsica', 'Europe', ' Corsica, France' ),
( @activeTopLevelDomain, 'cymru', 'Europe', ' Wales' ),
( @activeTopLevelDomain, 'eus', 'Europe', 'Basque, Spain and France' ),
( @activeTopLevelDomain, 'frl', 'Europe', ' Friesland, Netherlands' ),
( @activeTopLevelDomain, 'gal', 'Europe', 'Galiza, Spain' ),
( @activeTopLevelDomain, 'gent', 'Europe', 'Ghent, Belgium' ),
( @activeTopLevelDomain, 'hamburg', 'Europe', 'Hamburg, Germany' ),
( @activeTopLevelDomain, 'helsinki', 'Europe', 'Helsinki' ),
( @activeTopLevelDomain, 'irish', 'Europe', ' Ireland; global Irish community' ),
( @activeTopLevelDomain, 'ist', 'Europe', 'İstanbul, Turkey' ),
( @activeTopLevelDomain, 'istanbul', 'Europe', 'İstanbul, Turkey' ),
( @activeTopLevelDomain, 'koeln', 'Europe', 'Cologne, Germany' ),
( @activeTopLevelDomain, 'london', 'Europe', 'London, United Kingdom' ),
( @activeTopLevelDomain, 'madrid', 'Europe', 'Madrid, Spain' ),
( @activeTopLevelDomain, 'moscow (ru)', 'Europe', 'Moscow, Russia' ),
( @activeTopLevelDomain, 'nrw', 'Europe', 'North Rhine-Westphalia, Germany' ),
( @activeTopLevelDomain, 'paris', 'Europe', 'Paris, France' ),
( @activeTopLevelDomain, 'ruhr', 'Europe', 'Ruhr, Germany' ),
( @activeTopLevelDomain, 'saarland', 'Europe', ' Saarland, Germany' ),
( @activeTopLevelDomain, 'scot', 'Europe', ' Scotland' ),
( @activeTopLevelDomain, 'stockholm', 'Europe', 'Stockholm' ),
( @activeTopLevelDomain, 'swiss', 'Europe', '  Switzerland' ),
( @activeTopLevelDomain, 'tirol', 'Europe', ' Tyrol,Austria' ),
( @activeTopLevelDomain, 'vlaanderen', 'Europe', ' Flanders, Belgium' ),
( @activeTopLevelDomain, 'wales', 'Europe', ' Wales' ),
( @activeTopLevelDomain, 'wien', 'Europe', 'Vienna, Austria' ),
( @activeTopLevelDomain, 'zuerich', 'Europe', NULL ),
( @activeTopLevelDomain, 'boston', 'North America', 'Boston' ),
( @activeTopLevelDomain, 'miami', 'North America', 'Miami, USA' ),
( @activeTopLevelDomain, 'nyc', 'North America', 'New York City, USA' ),
( @activeTopLevelDomain, 'quebec', 'North America', 'Québec, Canada' )
;

  INSERT INTO @DataLoadTopLevelDomain ( RowStatus, TopLevelDomain, TopLevelDomainType, TopLevelDomainDescription )
  VALUES
( @activeTopLevelDomain, 'vegas', 'North America', NULL ),
( @activeTopLevelDomain, 'kiwi', 'Oceania', 'New Zealanders' ),
( @activeTopLevelDomain, 'melbourne', 'Oceania', 'Melbourne, Australia' ),
( @activeTopLevelDomain, 'sydney', 'Oceania', NULL ),
( @activeTopLevelDomain, 'lat', 'South America', 'Latin America' ),
( @activeTopLevelDomain, 'rio', 'South America', NULL ),
( @activeTopLevelDomain, 'aaa', 'Brand', 'American Automobile Association, Inc.' ),
( @activeTopLevelDomain, 'aarp', 'Brand', 'AARP' ),
( @activeTopLevelDomain, 'abarth', 'Brand', 'Fiat Chrysler Automobiles N.V.' ),
( @activeTopLevelDomain, 'abb', 'Brand', 'ABB Ltd' ),
( @activeTopLevelDomain, 'abbott', 'Brand', 'Abbott Laboratories, Inc.' ),
( @activeTopLevelDomain, 'abbvie', 'Brand', 'AbbVie Inc.' ),
( @activeTopLevelDomain, 'accenture', 'Brand', 'Accenture plc' ),
( @activeTopLevelDomain, 'aco', 'Brand', 'ACO Severin Ahlmann GmbH & Co. KG' ),
( @activeTopLevelDomain, 'aeg', 'Brand', 'Aktiebolaget Electrolux' ),
( @activeTopLevelDomain, 'aetna', 'Brand', 'Aetna Life Insurance Company' ),
( @activeTopLevelDomain, 'afl', 'Brand', 'Australian Football League' ),
( @activeTopLevelDomain, 'agakhan', 'Brand', 'Fondation Aga Khan (Aga Khan Foundation)' ),
( @activeTopLevelDomain, 'aig', 'Brand', 'American International Group, Inc.' ),
( @activeTopLevelDomain, 'aigo', 'Brand', 'aigo Digital Technology Co,Ltd.' ),
( @activeTopLevelDomain, 'airbus', 'Brand', 'Airbus S.A.S.' ),
( @activeTopLevelDomain, 'airtel', 'Brand', 'Bharti Airtel Limited' ),
( @activeTopLevelDomain, 'akdn', 'Brand', 'Fondation Aga Khan (Aga Khan Foundation)' ),
( @activeTopLevelDomain, 'alfaromeo', 'Brand', 'Fiat Chrysler Automobiles N.V.' ),
( @activeTopLevelDomain, 'alibaba', 'Brand', 'Alibaba Group Holding Limited' ),
( @activeTopLevelDomain, 'alipay', 'Brand', 'Alibaba Group Holding Limited' ),
( @activeTopLevelDomain, 'allfinanz', 'Brand', 'Allfinanz Deutsche Vermögensberatung Aktiengesellschaft' ),
( @activeTopLevelDomain, 'allstate', 'Brand', 'Allstate Fire and Casualty Insurance Company' ),
( @activeTopLevelDomain, 'ally', 'Brand', 'Ally Financial Inc.' ),
( @activeTopLevelDomain, 'alstom', 'Brand', 'ALSTOM' ),
( @activeTopLevelDomain, 'americanexpress', 'Brand', 'American Express Travel Related Services Company, Inc.' ),
( @activeTopLevelDomain, 'amex', 'Brand', 'American Express Travel Related Services Company, Inc.' ),
( @activeTopLevelDomain, 'amica', 'Brand', 'Amica Mutual Insurance Company' ),
( @activeTopLevelDomain, 'android', 'Brand', 'Google (Android)' ),
( @activeTopLevelDomain, 'anz', 'Brand', 'Australia and New Zealand Banking Group Limited' ),
( @activeTopLevelDomain, 'aol', 'Brand', 'AOL Inc.' ),
( @activeTopLevelDomain, 'apple', 'Brand', 'Apple Inc.' ),
( @activeTopLevelDomain, 'aquarelle', 'Brand', 'Aquarelle.com Group' ),
( @activeTopLevelDomain, 'aramco', 'Brand', 'Aramco Services Company' ),
( @activeTopLevelDomain, 'audi', 'Brand', 'AUDI Aktiengesellschaft' ),
( @activeTopLevelDomain, 'auspost', 'Brand', 'Australian Postal Corporation' ),
( @activeTopLevelDomain, 'axa', 'Brand', 'AXA' ),
( @activeTopLevelDomain, 'azure', 'Brand', 'Microsoft Corporation' ),
( @activeTopLevelDomain, 'baidu', 'Brand', 'Baidu, Inc.' ),
( @activeTopLevelDomain, 'barclaycard', 'Brand', 'Barclays' ),
( @activeTopLevelDomain, 'barclays', 'Brand', 'Barclays' ),
( @activeTopLevelDomain, 'bauhaus', 'Brand', 'Werkhaus GmbH' ),
( @activeTopLevelDomain, 'bbc', 'Brand', 'British Broadcasting Corporation' ),
( @activeTopLevelDomain, 'bbt', 'Brand', 'BB&T Corporation' ),
( @activeTopLevelDomain, 'bbva', 'Brand', 'Banco Bilbao Vizcaya Argentaria, S.A.' ),
( @activeTopLevelDomain, 'bcg', 'Brand', 'The Boston Consulting Group, Inc.' ),
( @activeTopLevelDomain, 'bentley', 'Brand', 'Bentley Motors Limited' ),
( @activeTopLevelDomain, 'bharti', 'Brand', 'Bharti Enterprises (Holding) Private Limited' ),
( @activeTopLevelDomain, 'bing', 'Brand', 'Microsoft Corporation' ),
( @activeTopLevelDomain, 'blanco', 'Brand', 'BLANCO GmbH + Co KG' ),
( @activeTopLevelDomain, 'bloomberg', 'Brand', 'Bloomberg IP Holdings LLC' ),
( @activeTopLevelDomain, 'bms', 'Brand', 'Bristol-Myers Squibb Company' ),
( @activeTopLevelDomain, 'bmw', 'Brand', 'Bayerische Motoren Werke AG' ),
( @activeTopLevelDomain, 'bnl', 'Brand', 'Banca Nazionale del Lavoro' ),
( @activeTopLevelDomain, 'bnpparibas', 'Brand', 'BNP Paribas' ),
( @activeTopLevelDomain, 'boehringer', 'Brand', 'Boehringer Ingelheim International GmbH' ),
( @activeTopLevelDomain, 'bond', 'Brand', 'Bond University Limited' ),
( @activeTopLevelDomain, 'booking', 'Brand', 'Booking.com B.V.' ),
( @activeTopLevelDomain, 'bosch', 'Brand', 'Robert Bosch GMBH' ),
( @activeTopLevelDomain, 'bostik', 'Brand', 'Bostik SA' ),
( @activeTopLevelDomain, 'bradesco', 'Brand', 'Bradesco' ),
( @activeTopLevelDomain, 'bridgestone', 'Brand', 'Bridgestone Corporation' ),
( @activeTopLevelDomain, 'brother', 'Brand', 'Brother Industries, Ltd.' ),
( @activeTopLevelDomain, 'bugatti', 'Brand', 'Bugatti International SA' ),
( @activeTopLevelDomain, 'cal', 'Brand', 'Google (Google Calendar)' ),
( @activeTopLevelDomain, 'calvinklein', 'Brand', 'PVH gTLD Holdings LLC' ),
( @activeTopLevelDomain, 'canon', 'Brand', 'Canon Inc.' ),
( @activeTopLevelDomain, 'capitalone', 'Brand', 'Capital One Financial Corporation' ),
( @activeTopLevelDomain, 'caravan', 'Brand', 'Caravan International, Inc.' ),
( @activeTopLevelDomain, 'cartier', 'Brand', 'Richemont DNS Inc.' ),
( @activeTopLevelDomain, 'cba', 'Brand', 'Commonwealth Bank Of Australia' ),
( @activeTopLevelDomain, 'cbn', 'Brand', 'The Christian Broadcasting Network, Inc.' ),
( @activeTopLevelDomain, 'cbre', 'Brand', 'CBRE, Inc.' ),
( @activeTopLevelDomain, 'cbs', 'Brand', 'CBS Domains Inc.' ),
( @activeTopLevelDomain, 'cern', 'Brand', 'CERN' ),
( @activeTopLevelDomain, 'cfa', 'Brand', 'CFA Institute' ),
( @activeTopLevelDomain, 'chanel', 'Brand', 'Chanel International B.V.' ),
( @activeTopLevelDomain, 'chase', 'Brand', 'JPMorgan Chase Bank, National Association' ),
( @activeTopLevelDomain, 'chintai', 'Brand', 'Chintai Corporation' ),
( @activeTopLevelDomain, 'chrome', 'Brand', 'Google (Google Chrome)' ),
( @activeTopLevelDomain, 'chrysler', 'Brand', 'FCA US LLC.' ),
( @activeTopLevelDomain, 'cisco', 'Brand', 'Cisco Technology, Inc.' ),
( @activeTopLevelDomain, 'citadel', 'Brand', 'Citadel Domain LLC' ),
( @activeTopLevelDomain, 'citi', 'Brand', 'Citigroup Inc.' ),
( @activeTopLevelDomain, 'citic', 'Brand', 'CITIC Group' ),
( @activeTopLevelDomain, 'clubmed', 'Brand', 'Club Méditerranée S.A.' ),
( @activeTopLevelDomain, 'comcast', 'Brand', 'Comcast IP Holdings I, LLC' ),
( @activeTopLevelDomain, 'commbank', 'Brand', 'Commonwealth Bank Of Australia' ),
( @activeTopLevelDomain, 'creditunion', 'Brand', 'CUNA Performance Resources, LLC' ),
( @activeTopLevelDomain, 'crown', 'Brand', 'Crown Equipment Corporation' ),
( @activeTopLevelDomain, 'crs', 'Brand', 'Federated Co-operatives Limited' ),
( @activeTopLevelDomain, 'cuisinella', 'Brand', 'Société Alsacienne de Meubles (Cuisinella)' ),
( @activeTopLevelDomain, 'dabur', 'Brand', 'Dabur India Limited' ),
( @activeTopLevelDomain, 'datsun', 'Brand', 'Nissan Motor Co., Ltd.' ),
( @activeTopLevelDomain, 'dealer', 'Brand', 'Dealer Dot Com, Inc.' ),
( @activeTopLevelDomain, 'dell', 'Brand', 'Dell Inc.' ),
( @activeTopLevelDomain, 'deloitte', 'Brand', 'Deloitte Touche Tohmatsu' ),
( @activeTopLevelDomain, 'delta', 'Brand', 'Delta Air Lines, Inc.' ),
( @activeTopLevelDomain, 'dhl', 'Brand', 'Deutsche Post AG' ),
( @activeTopLevelDomain, 'discover', 'Brand', 'Discover Financial Services' ),
( @activeTopLevelDomain, 'dish', 'Brand', 'Dish DBS Corporation' ),
( @activeTopLevelDomain, 'dnp', 'Brand', 'Dai Nippon Printing Co.' ),
( @activeTopLevelDomain, 'dodge', 'Brand', 'FCA US LLC.' ),
( @activeTopLevelDomain, 'dunlop', 'Brand', 'The Goodyear Tire & Rubber Company' ),
( @activeTopLevelDomain, 'dupont', 'Brand', 'E. I. du Pont de Nemours and Company' ),
( @activeTopLevelDomain, 'dvag', 'Brand', 'Deutsche Vermögensberatung Aktiengesellschaft' ),
( @activeTopLevelDomain, 'edeka', 'Brand', 'Edeka' ),
( @activeTopLevelDomain, 'emerck', 'Brand', 'Merck KGaA' ),
( @activeTopLevelDomain, 'epson', 'Brand', 'Seiko Epson Corporation' ),
( @activeTopLevelDomain, 'ericsson', 'Brand', 'Telefonaktiebolaget L M Ericsson' ),
( @activeTopLevelDomain, 'erni', 'Brand', 'ERNI Group Holding AG' ),
( @activeTopLevelDomain, 'esurance', 'Brand', 'Esurance Insurance Company' ),
( @activeTopLevelDomain, 'etisalat', 'Brand', 'Emirates Telecommunications Corporation (trading as Etisalat)' ),
( @activeTopLevelDomain, 'eurovision', 'Brand', 'European Broadcasting Union (EBU)' ),
( @activeTopLevelDomain, 'everbank', 'Brand', 'EverBank' ),
( @activeTopLevelDomain, 'extraspace', 'Brand', 'Extra Space Storage LLC' ),
( @activeTopLevelDomain, 'fage', 'Brand', 'Fage International S.A.' ),
( @activeTopLevelDomain, 'fairwinds', 'Brand', 'FairWinds Partners, LLC' ),
( @activeTopLevelDomain, 'farmers', 'Brand', 'Farmers Insurance Exchange' ),
( @activeTopLevelDomain, 'FedEx', 'Brand', 'Federal Express Corporation' ),
( @activeTopLevelDomain, 'ferrari', 'Brand', 'Fiat Chrysler Automobiles N.V.' ),
( @activeTopLevelDomain, 'ferrero', 'Brand', 'Ferrero Trading Lux S.A.' ),
( @activeTopLevelDomain, 'fiat', 'Brand', 'Fiat Chrysler Automobiles N.V.' ),
( @activeTopLevelDomain, 'fidelity', 'Brand', 'Fidelity Brokerage Services LLC' ),
( @activeTopLevelDomain, 'firestone', 'Brand', 'Bridgestone Licensing Services, Inc.' ),
( @activeTopLevelDomain, 'firmdale', 'Brand', 'Firmdale Holdings' ),
( @activeTopLevelDomain, 'flickr', 'Brand', 'Yahoo! Domain Services Inc.' ),
( @activeTopLevelDomain, 'flir', 'Brand', 'FLIR Systems, Inc.' ),
( @activeTopLevelDomain, 'flsmidth', 'Brand', 'FLSmidth A/S' ),
( @activeTopLevelDomain, 'ford', 'Brand', 'Ford Motor Company' ),
( @activeTopLevelDomain, 'fox', 'Brand', 'FOX Registry, LLC' ),
( @activeTopLevelDomain, 'fresenius', 'Brand', 'Fresenius Immobilien-Verwaltungs-GmbH' ),
( @activeTopLevelDomain, 'forex', 'Brand', 'Dotforex Registry Ltd' ),
( @activeTopLevelDomain, 'frogans', 'Brand', 'OP3FT' ),
( @activeTopLevelDomain, 'frontier', 'Brand', 'Frontier Communications Corporation' ),
( @activeTopLevelDomain, 'fujitsu', 'Brand', 'Fujitsu Limited' ),
( @activeTopLevelDomain, 'fujixerox', 'Brand', 'Xerox DNHC LLC' ),
( @activeTopLevelDomain, 'gallo', 'Brand', 'Gallo Vineyards, Inc.' ),
( @activeTopLevelDomain, 'gallup', 'Brand', 'Gallup, Inc.' ),
( @activeTopLevelDomain, 'gap', 'Brand', 'The Gap, Inc.' ),
( @activeTopLevelDomain, 'gbiz', 'Brand', 'Google' ),
( @activeTopLevelDomain, 'gea', 'Brand', 'GEA Group Aktiengesellschaft' ),
( @activeTopLevelDomain, 'genting', 'Brand', 'Resorts World Inc. Pte. Ltd.' ),
( @activeTopLevelDomain, 'giving', 'Brand', 'Giving Limited' ),
( @activeTopLevelDomain, 'gle', 'Brand', 'Google' ),
( @activeTopLevelDomain, 'globo', 'Brand', 'Grupo Globo' ),
( @activeTopLevelDomain, 'gmail', 'Brand', 'Google (Gmail)' ),
( @activeTopLevelDomain, 'gmo', 'Brand', 'GMO Internet' ),
( @activeTopLevelDomain, 'gmx', 'Brand', '1&1 Mail & Media (Global Message Exchange)' ),
( @activeTopLevelDomain, 'godaddy', 'Brand', 'Go Daddy East, LLC' ),
( @activeTopLevelDomain, 'goldpoint', 'Brand', 'Yodobashi Camera Co., Ltd.' ),
( @activeTopLevelDomain, 'goodyear', 'Brand', 'The Goodyear Tire & Rubber Company' ),
( @activeTopLevelDomain, 'google', 'Brand', 'Google' ),
( @activeTopLevelDomain, 'grainger', 'Brand', 'Grainger Registry Services, LLC' ),
( @activeTopLevelDomain, 'guardian', 'Brand', 'The Guardian Life Insurance Company of America' ),
( @activeTopLevelDomain, 'gucci', 'Brand', 'Guccio Gucci S.p.a.' ),
( @activeTopLevelDomain, 'hbo', 'Brand', 'HBO Registry Services, Inc.' ),
( @activeTopLevelDomain, 'hdfc', 'Brand', 'Housing Development Finance Corporation Limited' ),
( @activeTopLevelDomain, 'hdfcbank', 'Brand', 'HDFC Bank Limited' ),
( @activeTopLevelDomain, 'hermes', 'Brand', 'Hermes International' ),
( @activeTopLevelDomain, 'hisamitsu', 'Brand', 'Hisamitsu Pharmaceutical Co., Inc.' ),
( @activeTopLevelDomain, 'hitachi', 'Brand', 'Hitachi, Ltd.' ),
( @activeTopLevelDomain, 'hkt', 'Brand', 'PCCW-HKT DataCom Services Limited' ),
( @activeTopLevelDomain, 'honda', 'Brand', 'Honda Motor Co., Ltd.' ),
( @activeTopLevelDomain, 'honeywell', 'Brand', 'Honeywell GTLD LLC' ),
( @activeTopLevelDomain, 'hotmail', 'Brand', 'Microsoft Corporation' ),
( @activeTopLevelDomain, 'hsbc', 'Brand', 'HSBC' ),
( @activeTopLevelDomain, 'htc', 'Brand', 'HTC corporation' ),
( @activeTopLevelDomain, 'hughes', 'Brand', 'Hughes Satellite Systems Corporation' ),
( @activeTopLevelDomain, 'hyatt', 'Brand', 'Hyatt GTLD, L.L.C.' ),
( @activeTopLevelDomain, 'hyundai', 'Brand', 'Hyundai Motor Company' ),
( @activeTopLevelDomain, 'ibm', 'Brand', 'IBM' ),
( @activeTopLevelDomain, 'ieee', 'Brand', 'IEEE Global LLC' ),
( @activeTopLevelDomain, 'ifm', 'Brand', 'ifm electronic gmbh' ),
( @activeTopLevelDomain, 'ikano', 'Brand', 'Ikano S.A.' ),
( @activeTopLevelDomain, 'imdb', 'Brand', 'Amazon Registry Services, Inc.' ),
( @activeTopLevelDomain, 'infiniti', 'Brand', 'Nissan Motor Co., Ltd.' ),
( @activeTopLevelDomain, 'intel', 'Brand', 'Intel Corporation' ),
( @activeTopLevelDomain, 'intuit', 'Brand', 'Intuit Administrative Services, Inc.' ),
( @activeTopLevelDomain, 'ipiranga', 'Brand', 'Ipiranga Produtos de Petroleo S.A.' ),
( @activeTopLevelDomain, 'iselect', 'Brand', 'iSelect Ltd' ),
( @activeTopLevelDomain, 'itau', 'Brand', 'Itau Unibanco Holding S.A.' ),
( @activeTopLevelDomain, 'itv', 'Brand', 'ITV Services Limited' ),
( @activeTopLevelDomain, 'iveco', 'Brand', 'CNH Industrial N.V.' ),
( @activeTopLevelDomain, 'jaguar', 'Brand', 'Jaguar Land Rover Ltd' ),
( @activeTopLevelDomain, 'java', 'Brand', 'Oracle Corporation' ),
( @activeTopLevelDomain, 'jcb', 'Brand', 'JCB Co., Ltd.' ),
( @activeTopLevelDomain, 'jcp', 'Brand', 'JCP Media, Inc.' ),
( @activeTopLevelDomain, 'jeep', 'Brand', 'FCA US LLC.' ),
( @activeTopLevelDomain, 'jpmorgan', 'Brand', 'JPMorgan Chase Bank, National Association' ),
( @activeTopLevelDomain, 'juniper', 'Brand', 'Juniper Networks, Inc.' ),
( @activeTopLevelDomain, 'kddi', 'Brand', 'KDDI Corporation' ),
( @activeTopLevelDomain, 'kerryhotels', 'Brand', 'Kerry Trading Co. Limited' ),
( @activeTopLevelDomain, 'kerrylogistics', 'Brand', 'Kerry Trading Co. Limited' ),
( @activeTopLevelDomain, 'kerryproperties', 'Brand', 'Kerry Trading Co. Limited' ),
( @activeTopLevelDomain, 'kfh', 'Brand', 'Kuwait Finance House' ),
( @activeTopLevelDomain, 'kia', 'Brand', 'Kia Motors Corporation' ),
( @activeTopLevelDomain, 'kindle', 'Brand', 'Amazon Registry Services, Inc.' ),
( @activeTopLevelDomain, 'komatsu', 'Brand', 'Komatsu Ltd.' ),
( @activeTopLevelDomain, 'kpmg', 'Brand', 'KPMG International Cooperative (KPMG International Genossenschaft)' ),
( @activeTopLevelDomain, 'kred', 'Brand', 'KredTLD' ),
( @activeTopLevelDomain, 'kuokgroup', 'Brand', 'Kerry Trading Co. Limited' ),
( @activeTopLevelDomain, 'lacaixa', 'Brand', 'Caixa d’Estalvis i Pensions de Barcelona' ),
( @activeTopLevelDomain, 'ladbrokes', 'Brand', 'Ladbrokes International PLC' ),
( @activeTopLevelDomain, 'lamborghini', 'Brand', 'Automobili Lamborghini S.p.A.' ),
( @activeTopLevelDomain, 'lancaster', 'Brand', 'Lancaster' ),
( @activeTopLevelDomain, 'lancia', 'Brand', 'Fiat Chrysler Automobiles N.V.' ),
( @activeTopLevelDomain, 'lancome', 'Brand', 'L''Oréal' ),
( @activeTopLevelDomain, 'landrover', 'Brand', 'Jaguar Land Rover Ltd' ),
( @activeTopLevelDomain, 'lanxess', 'Brand', 'Lanxess Corporation' ),
( @activeTopLevelDomain, 'lasalle', 'Brand', 'Jones Lang LaSalle Incorporated' ),
( @activeTopLevelDomain, 'latrobe', 'Brand', 'La Trobe University' ),
( @activeTopLevelDomain, 'lds', 'Brand', 'The Church of Jesus Christ of Latter-day Saints (LDS Church)[198]' ),
( @activeTopLevelDomain, 'lego', 'Brand', 'LEGO Juris A/S' ),
( @activeTopLevelDomain, 'liaison', 'Brand', 'Liaison Technologies, Incorporated' ),
( @activeTopLevelDomain, 'lexus', 'Brand', 'Toyota Motor Corporation' ),
( @activeTopLevelDomain, 'lidl', 'Brand', 'Schwarz Domains und Services GmbH & Co. KG' ),
( @activeTopLevelDomain, 'lifestyle', 'Brand', 'Lifestyle Domain Holdings, Inc.' ),
( @activeTopLevelDomain, 'lilly', 'Brand', 'Eli Lilly and Company' ),
( @activeTopLevelDomain, 'lincoln', 'Brand', 'Ford Motor Company' ),
( @activeTopLevelDomain, 'linde', 'Brand', 'Linde Aktiengesellschaft' ),
( @activeTopLevelDomain, 'lipsy', 'Brand', 'Lipsy Ltd' ),
( @activeTopLevelDomain, 'lixil', 'Brand', 'LIXIL Group Corporation' ),
( @activeTopLevelDomain, 'locus', 'Brand', 'Locus Analytics LLC' ),
( @activeTopLevelDomain, 'lotte', 'Brand', 'Lotte Holdings Co., Ltd.' ),
( @activeTopLevelDomain, 'lpl', 'Brand', 'LPL Holdings, Inc.' ),
( @activeTopLevelDomain, 'lplfinancial', 'Brand', 'LPL Holdings, Inc.' ),
( @activeTopLevelDomain, 'lundbeck', 'Brand', 'H. Lundbeck A/S' ),
( @activeTopLevelDomain, 'lupin', 'Brand', 'Lupin Limited' ),
( @activeTopLevelDomain, 'macys', 'Brand', 'Macys, Inc.' ),
( @activeTopLevelDomain, 'maif', 'Brand', 'Mutuelle Assurance Instituteur France (MAIF)' ),
( @activeTopLevelDomain, 'man', 'Brand', 'MAN SE' ),
( @activeTopLevelDomain, 'mango', 'Brand', 'MANGO' ),
( @activeTopLevelDomain, 'marriott', 'Brand', 'Marriott Worldwide Corporation' ),
( @activeTopLevelDomain, 'maserati', 'Brand', 'Fiat Chrysler Automobiles N.V.' ),
( @activeTopLevelDomain, 'mattel', 'Brand', 'Mattel Sites, Inc.' ),
( @activeTopLevelDomain, 'mcd', 'Brand', 'McDonald’s Corporation' ),
( @activeTopLevelDomain, 'mcdonalds', 'Brand', 'McDonald’s Corporation' ),
( @activeTopLevelDomain, 'mckinsey', 'Brand', 'McKinsey Holdings, Inc.' ),
( @activeTopLevelDomain, 'meo', 'Brand', 'MEO Serviços de Comunicações e Multimédia, S.A.' ),
( @activeTopLevelDomain, 'metlife', 'Brand', 'MetLife Services and Solutions, LLC' ),
( @activeTopLevelDomain, 'microsoft', 'Brand', 'Microsoft Corporation' ),
( @activeTopLevelDomain, 'mini', 'Brand', 'BMW (Mini)' ),
( @activeTopLevelDomain, 'mit', 'Brand', 'Massachusetts Institute of Technology' ),
( @activeTopLevelDomain, 'mitsubishi', 'Brand', 'Mitsubishi Corporation' ),
( @activeTopLevelDomain, 'mlb', 'Brand', 'MLB Advanced Media DH, LLC' ),
( @activeTopLevelDomain, 'mma', 'Brand', 'MMA IARD' ),
( @activeTopLevelDomain, 'monash', 'Brand', 'Monash University' ),
( @activeTopLevelDomain, 'mormon', 'Brand', 'The Church of Jesus Christ of Latter-day Saints (LDS Church)[198]' ),
( @activeTopLevelDomain, 'moto', 'Brand', 'Motorola Trademark Holdings, LLC' ),
( @activeTopLevelDomain, 'movistar', 'Brand', 'Telefónica S.A.' ),
( @activeTopLevelDomain, 'msd', 'Brand', 'MSD Registry Holdings, Inc.' ),
( @activeTopLevelDomain, 'mtn', 'Brand', 'MTN Dubai Limited' ),
( @activeTopLevelDomain, 'mtpc', 'Brand', 'Mitsubishi Tanabe Pharma Corporation' ),
( @activeTopLevelDomain, 'mtr', 'Brand', 'MTR Corporation Limited' ),
( @activeTopLevelDomain, 'mutual', 'Brand', 'Northwestern Mutual MU TLD Registry, LLC' ),
( @activeTopLevelDomain, 'mutuelle', 'Brand', 'Fédération Nationale de la Mutualité Française' ),
( @activeTopLevelDomain, 'nadex', 'Brand', 'Nadex Domains, Inc' ),
( @activeTopLevelDomain, 'nationwide', 'Brand', 'Nationwide Mutual Insurance Company' ),
( @activeTopLevelDomain, 'natura', 'Brand', 'Natura Cosméticos S.A.' ),
( @activeTopLevelDomain, 'nba', 'Brand', 'NBA Registry, LLC' ),
( @activeTopLevelDomain, 'nec', 'Brand', 'NEC Corporation' ),
( @activeTopLevelDomain, 'netflix', 'Brand', 'Netflix, Inc.' ),
( @activeTopLevelDomain, 'neustar', 'Brand', 'Neustar' ),
( @activeTopLevelDomain, 'newholland', 'Brand', 'CNH Industrial N.V.' ),
( @activeTopLevelDomain, 'nexus', 'Brand', 'Google (Google Nexus)' ),
( @activeTopLevelDomain, 'nfl', 'Brand', 'NFL Reg Ops LLC' ),
( @activeTopLevelDomain, 'nhk', 'Brand', 'NHK' ),
( @activeTopLevelDomain, 'nico', 'Brand', 'Dwango Co., Ltd. (Niconico)' ),
( @activeTopLevelDomain, 'nike', 'Brand', 'Nike, Inc.' ),
( @activeTopLevelDomain, 'nikon', 'Brand', 'Nikon Corporation' ),
( @activeTopLevelDomain, 'nissan', 'Brand', 'Nissan Motor Co., Ltd.' ),
( @activeTopLevelDomain, 'nissay', 'Brand', 'Nippon Life Insurance Company' ),
( @activeTopLevelDomain, 'nokia', 'Brand', 'Nokia Corporation' ),
( @activeTopLevelDomain, 'northwesternmutual', 'Brand', 'Northwestern Mutual Registry, LLC' ),
( @activeTopLevelDomain, 'norton', 'Brand', 'Symantec Corporation' ),
( @activeTopLevelDomain, 'nra', 'Brand', 'National Rifle Association' ),
( @activeTopLevelDomain, 'ntt', 'Brand', 'Nippon Telegraph And Telephone Corporation' ),
( @activeTopLevelDomain, 'obi', 'Brand', 'OBI Group Holding SE & Co. KGaA' ),
( @activeTopLevelDomain, 'office', 'Brand', 'Microsoft Corporation' ),
( @activeTopLevelDomain, 'omega', 'Brand', 'The Swatch Group Ltd' ),
( @activeTopLevelDomain, 'oracle', 'Brand', 'Oracle Corporation' ),
( @activeTopLevelDomain, 'orange', 'Brand', 'Orange Brand Services Limited' ),
( @activeTopLevelDomain, 'orientexpress', 'Brand', 'Orient Express' ),
( @activeTopLevelDomain, 'otsuka', 'Brand', 'Otsuka Holdings' ),
( @activeTopLevelDomain, 'ovh', 'Brand', 'OVH' ),
( @activeTopLevelDomain, 'pamperedchef', 'Brand', 'The Pampered Chef, Ltd.' ),
( @activeTopLevelDomain, 'panasonic', 'Brand', 'Panasonic Corporation' ),
( @activeTopLevelDomain, 'pccw', 'Brand', 'PCCW Enterprises Limited' ),
( @activeTopLevelDomain, 'pfizer', 'Brand', 'Pfizer Inc.' ),
( @activeTopLevelDomain, 'philips', 'Brand', 'Koninklijke Philips N.V.' ),
( @activeTopLevelDomain, 'piaget', 'Brand', 'Piaget SA' ),
( @activeTopLevelDomain, 'pictet', 'Brand', 'Pictet Europe S.A.' ),
( @activeTopLevelDomain, 'ping', 'Brand', 'Ping Registry Provider, Inc.' ),
( @activeTopLevelDomain, 'pioneer', 'Brand', 'Pioneer Corporation' ),
( @activeTopLevelDomain, 'play', 'Brand', 'Charleston Road Registry Inc.' ),
( @activeTopLevelDomain, 'playstation', 'Brand', 'Sony Computer Entertainment Inc.' ),
( @activeTopLevelDomain, 'pohl', 'Brand', 'Deutsche Vermögensberatung Aktiengesellschaft' ),
( @activeTopLevelDomain, '  ', 'Brand', '(founder Reinfried Pohl)' ),
( @activeTopLevelDomain, 'politie', 'Brand', 'Politie Nederland' ),
( @activeTopLevelDomain, 'praxi', 'Brand', 'Praxi' ),
( @activeTopLevelDomain, 'prod', 'Brand', 'Google (products)' ),
( @activeTopLevelDomain, 'progressive', 'Brand', 'Progressive Casualty Insurance Company' ),
( @activeTopLevelDomain, 'pru', 'Brand', 'Prudential Financial, Inc.' ),
( @activeTopLevelDomain, 'prudential', 'Brand', 'Prudential Financial, Inc.' ),
( @activeTopLevelDomain, 'pwc', 'Brand', 'PwC' ),
( @activeTopLevelDomain, 'quest', 'Brand', 'Quest ION Limited' ),
( @activeTopLevelDomain, 'qvc', 'Brand', 'QVC, Inc.' ),
( @activeTopLevelDomain, 'redstone', 'Brand', 'Redstone Haute Couture Co., Ltd.' ),
( @activeTopLevelDomain, 'reliance', 'Brand', 'Reliance Industries Limited' ),
( @activeTopLevelDomain, 'rexroth', 'Brand', 'Robert Bosch GMBH' ),
( @activeTopLevelDomain, 'ricoh', 'Brand', 'Ricoh Company, Ltd.' ),
( @activeTopLevelDomain, 'rmit', 'Brand', 'Royal Melbourne Institute of Technology' ),
( @activeTopLevelDomain, 'rocher', 'Brand', 'Ferrero Trading Lux S.A.' ),
( @activeTopLevelDomain, 'rogers', 'Brand', 'Rogers Communications Canada Inc.' ),
( @activeTopLevelDomain, 'rwe', 'Brand', 'RWE AG' ),
( @activeTopLevelDomain, 'safety', 'Brand', 'Safety Registry Services, LLC.' ),
( @activeTopLevelDomain, 'sakura', 'Brand', 'SAKURA Internet Inc.' ),
( @activeTopLevelDomain, 'samsung', 'Brand', 'SAMSUNG SDS CO., LTD' ),
( @activeTopLevelDomain, 'sandvik', 'Brand', 'Sandvik AB' ),
( @activeTopLevelDomain, 'sandvikcoromant', 'Brand', 'Sandvik Coromant' ),
( @activeTopLevelDomain, 'sanofi', 'Brand', 'Sanofi' ),
( @activeTopLevelDomain, 'sap', 'Brand', 'SAP SE' ),
( @activeTopLevelDomain, 'saxo', 'Brand', 'Saxo Bank A/S' ),
( @activeTopLevelDomain, 'sbi', 'Brand', 'State Bank of India' ),
( @activeTopLevelDomain, 'sbs', 'Brand', 'Special Broadcasting Service Corporation' ),
( @activeTopLevelDomain, 'sca', 'Brand', 'Svenska Cellulosa Aktiebolaget' ),
( @activeTopLevelDomain, 'scb', 'Brand', 'Siam Commercial Bank' ),
( @activeTopLevelDomain, 'schaeffler', 'Brand', 'Schaeffler Technologies AG & Co. KG' ),
( @activeTopLevelDomain, 'schmidt', 'Brand', 'Société Alsacienne de Meubles (Cuisines Schmidt)' ),
( @activeTopLevelDomain, 'schwarz', 'Brand', 'Schwarz Domains und Services GmbH & Co. KG' ),
( @activeTopLevelDomain, 'scjohnson', 'Brand', 'Johnson Shareholdings, Inc.' ),
( @activeTopLevelDomain, 'scor', 'Brand', 'SCOR SE' ),
( @activeTopLevelDomain, 'seat', 'Brand', 'SEAT, S.A. (Sociedad Unipersonal)' ),
( @activeTopLevelDomain, 'sener', 'Brand', 'Sener Ingeniería y Sistemas, S.A.' ),
( @activeTopLevelDomain, 'ses', 'Brand', 'SES' ),
( @activeTopLevelDomain, 'sew', 'Brand', 'SEW-EURODRIVE GmbH & Co KG' ),
( @activeTopLevelDomain, 'seven', 'Brand', 'Seven West Media Ltd' ),
( @activeTopLevelDomain, 'sfr', 'Brand', 'Societe Francaise du Radiotelephone - SFR' ),
( @activeTopLevelDomain, 'seek', 'Brand', 'Seek Limited' ),
( @activeTopLevelDomain, 'shangrila', 'Brand', 'Shangri‐La International Hotel Management Limited' ),
( @activeTopLevelDomain, 'sharp', 'Brand', 'Sharp Corporation' ),
( @activeTopLevelDomain, 'shaw', 'Brand', 'Shaw Cablesystems G.P.' ),
( @activeTopLevelDomain, 'shell', 'Brand', 'Shell Information Technology International Inc' ),
( @activeTopLevelDomain, 'shriram', 'Brand', 'Shriram Capital Ltd.' ),
( @activeTopLevelDomain, 'sina', 'Brand', 'Sina Corporation' ),
( @activeTopLevelDomain, 'skype', 'Brand', 'Microsoft Corporation' ),
( @activeTopLevelDomain, 'smart', 'Brand', 'Smart Communications, Inc. (SMART)' ),
( @activeTopLevelDomain, 'sncf', 'Brand', 'SNCF (Société Nationale des Chemins de fer Francais)' ),
( @activeTopLevelDomain, 'softbank', 'Brand', 'SoftBank Group Corp.' ),
( @activeTopLevelDomain, 'sohu', 'Brand', 'Sohu' ),
( @activeTopLevelDomain, 'Sony', 'Brand', 'Sony Corporation' ),
( @activeTopLevelDomain, 'spiegel', 'Brand', 'Spiegel-Verlag' ),
( @activeTopLevelDomain, 'stada', 'Brand', 'STADA Arzneimittel AG' ),
( @activeTopLevelDomain, 'staples', 'Brand', 'Staples, Inc.' ),
( @activeTopLevelDomain, 'star', 'Brand', 'Star India Private Limited' ),
( @activeTopLevelDomain, 'starhub', 'Brand', 'StarHub Limited' ),
( @activeTopLevelDomain, 'statebank', 'Brand', 'State Bank of India' ),
( @activeTopLevelDomain, 'statefarm', 'Brand', 'State Farm Mutual Automobile Insurance Company' ),
( @activeTopLevelDomain, 'statoil', 'Brand', 'Statoil ASA' ),
( @activeTopLevelDomain, 'stc', 'Brand', 'Saudi Telecom Company' ),
( @activeTopLevelDomain, 'stcgroup', 'Brand', 'Saudi Telecom Company' ),
( @activeTopLevelDomain, 'suzuki', 'Brand', 'Suzuki Motor Corporation' ),
( @activeTopLevelDomain, 'swatch', 'Brand', 'The Swatch Group Ltd' ),
( @activeTopLevelDomain, 'swiftcover', 'Brand', 'Swiftcover Insurance Services Limited' ),
( @activeTopLevelDomain, 'symantec', 'Brand', 'Symantec Corporation' ),
( @activeTopLevelDomain, 'taobao', 'Brand', 'Alibaba Group Holding Limited' ),
( @activeTopLevelDomain, 'target', 'Brand', 'Target Domain Holdings, LLC' ),
( @activeTopLevelDomain, 'tatamotors', 'Brand', 'Tata Motors Ltd' ),
( @activeTopLevelDomain, 'tdk', 'Brand', 'TDK Corporation' ),
( @activeTopLevelDomain, 'telecity', 'Brand', 'TelecityGroup International Limited' ),
( @activeTopLevelDomain, 'telefonica', 'Brand', 'Telefónica S.A.' ),
( @activeTopLevelDomain, 'temasek', 'Brand', 'Temasek Holdings (Private) Limited' ),
( @activeTopLevelDomain, 'teva', 'Brand', 'Teva Pharmaceutical Industries Limited' ),
( @activeTopLevelDomain, 'tiffany', 'Brand', 'Tiffany and Company' ),
( @activeTopLevelDomain, 'tjx', 'Brand', 'The TJX Companies, Inc.' ),
( @activeTopLevelDomain, 'toray', 'Brand', 'Toray Industries, Inc.' ),
( @activeTopLevelDomain, 'toshiba', 'Brand', 'TOSHIBA Corporation' ),
( @activeTopLevelDomain, 'total', 'Brand', 'Total SA' ),
( @activeTopLevelDomain, 'toyota', 'Brand', 'Toyota Motor Corporation' ),
( @activeTopLevelDomain, 'travelchannel', 'Brand', 'Lifestyle Domain Holdings, Inc.' ),
( @activeTopLevelDomain, 'travelers', 'Brand', 'Travelers TLD, LLC' ),
( @activeTopLevelDomain, 'tui', 'Brand', 'TUI AG' ),
( @activeTopLevelDomain, 'tvs', 'Brand', 'T V Sundram Iyengar & Sons Private Limited' ),
( @activeTopLevelDomain, 'ubs', 'Brand', 'UBS AG' ),
( @activeTopLevelDomain, 'unicom', 'Brand', 'China United Network Communications Corporation Limited' ),
( @activeTopLevelDomain, 'uol', 'Brand', 'Universo Online' ),
( @activeTopLevelDomain, 'ups', 'Brand', 'UPS Market Driver, Inc.' ),
( @activeTopLevelDomain, 'vanguard', 'Brand', 'The Vanguard Group, Inc.' ),
( @activeTopLevelDomain, 'verisign', 'Brand', 'VeriSign, Inc.' ),
( @activeTopLevelDomain, 'vig', 'Brand', 'Vienna Insurance Group AG Wiener Versicherung Gruppe' ),
( @activeTopLevelDomain, 'viking', 'Brand', 'Viking River Cruises (Bermuda) Ltd.' ),
( @activeTopLevelDomain, 'virgin', 'Brand', 'Virgin Enterprises Limited' ),
( @activeTopLevelDomain, 'visa', 'Brand', 'Visa Worldwide Pte. Limited' ),
( @activeTopLevelDomain, 'vista', 'Brand', 'Vistaprint Limited' ),
( @activeTopLevelDomain, 'vistaprint', 'Brand', 'Vistaprint Limited' ),
( @activeTopLevelDomain, 'vivo', 'Brand', 'Telefónica Brasil S.A.' ),
( @activeTopLevelDomain, 'volkswagen', 'Brand', 'Volkswagen Group of America Inc.' ),
( @activeTopLevelDomain, 'volvo', 'Brand', 'Volvo Holding Sverige Aktiebolag' ),
( @activeTopLevelDomain, 'walmart', 'Brand', 'Wal-Mart Stores, Inc.' ),
( @activeTopLevelDomain, 'walter', 'Brand', 'Sandvik AB' ),
( @activeTopLevelDomain, 'weatherchannel', 'Brand', 'International Business Machines Corporation' ),
( @activeTopLevelDomain, 'weber', 'Brand', 'Saint-Gobain Weber SA' ),
( @activeTopLevelDomain, 'weir', 'Brand', 'Weir Group IP Limited' ),
( @activeTopLevelDomain, 'williamhill', 'Brand', 'William Hill' ),
( @activeTopLevelDomain, 'windows', 'Brand', 'Microsoft Corporation' ),
( @activeTopLevelDomain, 'wme', 'Brand', 'William Morris Endeavor Entertainment' ),
( @activeTopLevelDomain, 'wolterskluwer', 'Brand', 'Wolters Kluwer N.V.' ),
( @activeTopLevelDomain, 'woodside', 'Brand', 'Woodside Petroleum Limited' ),
( @activeTopLevelDomain, 'wtc', 'Brand', 'World Trade Centers Association' ),
( @activeTopLevelDomain, 'xbox', 'Brand', 'Microsoft Corporation' ),
( @activeTopLevelDomain, 'xerox', 'Brand', 'Xerox DNHC LLC' ),
( @activeTopLevelDomain, 'xfinity', 'Brand', 'Comcast IP Holdings I, LLC' ),
( @activeTopLevelDomain, 'xperia', 'Brand', 'Sony Mobile Communications AB' ),
( @activeTopLevelDomain, 'yahoo', 'Brand', 'Yahoo! Domain Services Inc.' ),
( @activeTopLevelDomain, 'yamaxun', 'Brand', 'Amazon Registry Services, Inc.' ),
( @activeTopLevelDomain, 'yandex', 'Brand', 'Yandex' ),
( @activeTopLevelDomain, 'yodobashi', 'Brand', 'YODOBASHI CAMERA CO.,LTD.' ),
( @activeTopLevelDomain, 'youtube', 'Brand', 'Google (YouTube)' ),
( @activeTopLevelDomain, 'zappos', 'Brand', 'Amazon Registry Services, Inc.' ),
( @activeTopLevelDomain, 'zara', 'Brand', 'Industria de Diseño Textil, S.A. (INDITEX, S.A.)' ),
( @activeTopLevelDomain, 'zip', 'Brand', 'Charleston Road Registry Inc.' ),
( @activeTopLevelDomain, 'zippo', 'Brand', NULL ),
( @activeTopLevelDomain, 'example', 'Special Use', NULL ),
( @activeTopLevelDomain, 'invalid', 'Special Use', NULL ),
( @activeTopLevelDomain, 'local', 'Special Use', NULL ),
( @activeTopLevelDomain, 'localhost', 'Special Use', NULL ),
( @activeTopLevelDomain, 'onion', 'Special Use', NULL ),
( @activeTopLevelDomain, 'test', 'Special Use', NULL )
  ;
  
  -- We need a var to hold the total number of records we are going to try and dataload
  DECLARE @TotalDataLoadRecordsTopLevelDomain INT;
  SELECT @TotalDataLoadRecordsTopLevelDomain = COUNT(1) FROM @DataLoadTopLevelDomain;

  -- We need to reset our loop counter var
  SET @CtrTopLevelDomain = 1;

  -- Loop over each record, attempt to load it. If the record exists, status it with the Found status
  WHILE ( @CtrTopLevelDomain < = @TotalDataLoadRecordsTopLevelDomain )
  BEGIN

      IF NOT EXISTS 
      ( 
        SELECT  1
        FROM    masterLists.TopLevelDomain AS TopLevelDomain WITH (nolock)
        WHERE   TopLevelDomain.TopLevelDomain = ( SELECT DataLoad.TopLevelDomain 
                                           FROM @DataLoadTopLevelDomain AS DataLoad
                                           WHERE RowCounter = @CtrTopLevelDomain )
      ) 
      BEGIN

        INSERT INTO [MasterLists].[TopLevelDomain] ( 
        [TopLevelDomain], 
        [RowStatus],
        [CreatedBy],
        [ModifiedBy],
        [CreatedDate],
        [ModifiedDate],
        [RowGuid], 
        [TopLevelDomainType], 
        TopLevelDomainDescription)
        OUTPUT inserted.TopLevelDomain, inserted.RowStatus, inserted.CreatedBy, inserted.ModifiedBy, inserted.CreatedDate, inserted.ModifiedDate, inserted.RowGuid, inserted.TopLevelDomainType, inserted.TopLevelDomainDescription INTO @DataLoadTopLevelDomainOutput
        SELECT
          DataLoad.TopLevelDomain,
          @activeTopLevelDomain,
          @CreatedByTopLevelDomain,
          @CreatedByTopLevelDomain,
          GETUTCDATE(),
          GETUTCDATE(),
          NEWID(),
          DataLoad.TopLevelDomainType,
          Dataload.TopLevelDomainDescription
        FROM
          @DataLoadTopLevelDomain AS DataLoad
        WHERE
          RowCounter = @CtrTopLevelDomain

      END

      ELSE
      BEGIN
      
        -- The record exists, just add it to our output statused appropriately
        INSERT INTO @DataLoadTopLevelDomainOutput ( TopLevelDomain, TopLevelDomainType, RowStatus, CreatedBy, ModifiedBy, CreatedDate, ModifiedDate, RowGuid, TopLevelDomainDescription )
        SELECT
          TopLevelDomain.TopLevelDomain,
          TopLevelDomain.TopLevelDomainType,
          @RecordExistsTopLevelDomain,
          TopLevelDomain.CreatedBy,
          TopLevelDomain.ModifiedBy,
          TopLevelDomain.CreatedDate,
          TopLevelDomain.CreatedDate,
          TopLevelDomain.RowGuid,
          TopLevelDomain.TopLevelDomainDescription
        FROM    
          MasterLists.TopLevelDomain AS TopLevelDomain WITH (nolock)
          
          INNER JOIN @DataLoadTopLevelDomain AS DataLoad
          ON TopLevelDomain.TopLevelDomain = DataLoad.TopLevelDomain

        WHERE   
          TopLevelDomain.TopLevelDomain = ( SELECT DataLoad.TopLevelDomain 
                                     FROM @DataLoadTopLevelDomain AS DataLoad
                                     WHERE RowCounter = @CtrTopLevelDomain )       
         
      END -- end if exists

      -- Increase our counter by 1
      SET @CtrTopLevelDomain = @CtrTopLevelDomain + 1;

  END -- end while

  -- Show the results
  SELECT * FROM @DataLoadTopLevelDomainOutput

  COMMIT TRANSACTION;

END TRY
BEGIN CATCH

  -- Error trapping vars
  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;      

  DECLARE 
    @ErrMessageTopLevelDomain       nvarchar(2048),
    @ErrSeverityTopLevelDomain      tinyint,
    @ErrStateTopLevelDomain         tinyint,
    @ErrNumberTopLevelDomain        int,
    @ErrProcedureTopLevelDomain     sysname,
    @ErrLineTopLevelDomain          int
              
  SELECT 
    @ErrNumberTopLevelDomain    = ERROR_NUMBER(),
    @ErrSeverityTopLevelDomain  = ERROR_SEVERITY(),
    @ErrStateTopLevelDomain     = ERROR_STATE(),
    @ErrProcedureTopLevelDomain = ERROR_PROCEDURE(),
    @ErrLineTopLevelDomain      = ERROR_LINE(),
    @ErrMessageTopLevelDomain   = ERROR_MESSAGE();

  EXECUTE [eventLogs].[DatabaseErrorHandler]
    @ErrorNumber    = @ErrNumberTopLevelDomain,
    @ErrorSeverity  = @ErrSeverityTopLevelDomain,
    @ErrorState     = @ErrStateTopLevelDomain,
    @ErrorProcedure = @ErrProcedureTopLevelDomain,
    @ErrorLine      = @ErrLineTopLevelDomain,
    @ErrorMessage   = @ErrMessageTopLevelDomain

  --re-raise the error
  RAISERROR ( @ErrMessageTopLevelDomain, @ErrSeverityTopLevelDomain, @ErrStateTopLevelDomain )

END CATCH
